# coding: utf-8

"""
    Geometry Backend API v2

    The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.

    The version of the OpenAPI document: 1.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from shapediver.geometry_api_v2.client.models.req_output_definition_chunk import ReqOutputDefinitionChunk
from shapediver.geometry_api_v2.client.models.req_output_definition_group import ReqOutputDefinitionGroup
from typing import Optional, Set
from typing_extensions import Self

class ReqOutputDefinition(BaseModel):
    """
    Data for a single output definition.
    """ # noqa: E501
    displayname: Optional[StrictStr] = Field(default=None, description="Parameter name to display instead of `name`.")
    group: Optional[ReqOutputDefinitionGroup] = None
    hidden: Optional[StrictBool] = Field(default=None, description="Controls whether the output should be hidden in the UI.")
    order: Optional[StrictInt] = Field(default=None, description="Ordering of the output in client applications.")
    tooltip: Optional[StrictStr] = Field(default=None, description="Description that is shown as a tooltip in the clients.")
    chunks: Optional[List[ReqOutputDefinitionChunk]] = Field(default=None, description="The chunk definitions of the sdTF file that is generated by the output. If specified, all existing sdTF chunks of the output must be given. The order of the given chunk items determines the order in that the chunks will be shown in the UI.")
    __properties: ClassVar[List[str]] = ["displayname", "group", "hidden", "order", "tooltip", "chunks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReqOutputDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in chunks (list)
        _items = []
        if self.chunks:
            for _item in self.chunks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['chunks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReqOutputDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "displayname": obj.get("displayname"),
            "group": ReqOutputDefinitionGroup.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "hidden": obj.get("hidden"),
            "order": obj.get("order"),
            "tooltip": obj.get("tooltip"),
            "chunks": [ReqOutputDefinitionChunk.from_dict(_item) for _item in obj["chunks"]] if obj.get("chunks") is not None else None
        })
        return _obj


