# coding: utf-8

"""
    Geometry Backend API v2

    The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.

    The version of the OpenAPI document: 2.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResModelSessionStatistics(BaseModel):
    """
    ResModelSessionStatistics
    """ # noqa: E501
    billable_count: StrictInt = Field(description="Number of billing windows started during the session (timeslot pricing).", alias="billableCount")
    duration: StrictInt = Field(description="Total duration of the session in milliseconds.")
    exports_count: StrictInt = Field(description="Number of successful export requests that did not also request outputs.", alias="exportsCount")
    interactions_count: StrictInt = Field(description="Number of successful customization requests.", alias="interactionsCount")
    combined_count: StrictInt = Field(description="Number of successful export requests that also requested outputs.", alias="combinedCount")
    __properties: ClassVar[List[str]] = ["billableCount", "duration", "exportsCount", "interactionsCount", "combinedCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResModelSessionStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResModelSessionStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "billableCount": obj.get("billableCount"),
            "duration": obj.get("duration"),
            "exportsCount": obj.get("exportsCount"),
            "interactionsCount": obj.get("interactionsCount"),
            "combinedCount": obj.get("combinedCount")
        })
        return _obj


