# coding: utf-8

"""
    Geometry Backend API v2

    The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.

    The version of the OpenAPI document: 2.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from shapediver.geometry_api_v2.client.models.res_model_session_request import ResModelSessionRequest
from shapediver.geometry_api_v2.client.models.res_model_session_statistics import ResModelSessionStatistics
from shapediver.geometry_api_v2.client.models.session_analytics_status import SessionAnalyticsStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResModelSession(BaseModel):
    """
    ResModelSession
    """ # noqa: E501
    id: StrictStr = Field(description="ID of the session. The value may be redacted.")
    status: SessionAnalyticsStatus
    opened_at: Annotated[str, Field(strict=True)] = Field(description="A ISO-8601 date-time, in numeric format.  Format: YYYYMMDDhhmmsszzz", alias="openedAt", json_schema_extra={"examples": ["20240521140735123"]})
    closed_at: Optional[Annotated[str, Field(strict=True)]] = Field(description="A ISO-8601 date-time, in numeric format.  Format: YYYYMMDDhhmmsszzz", alias="closedAt", json_schema_extra={"examples": ["20240521140735123"]})
    statistics: Optional[ResModelSessionStatistics] = None
    charge_user_id: Optional[StrictStr] = Field(default=None, alias="chargeUserId")
    charge_org_id: Optional[StrictStr] = Field(default=None, alias="chargeOrgId")
    request: Optional[ResModelSessionRequest] = None
    __properties: ClassVar[List[str]] = ["id", "status", "openedAt", "closedAt", "statistics", "chargeUserId", "chargeOrgId", "request"]

    @field_validator('opened_at', mode="before")
    def opened_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^\d{17}$", value):
            raise ValueError(r"must validate the regular expression /^\d{17}$/")
        return value

    @field_validator('closed_at', mode="before")
    def closed_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^\d{17}$", value):
            raise ValueError(r"must validate the regular expression /^\d{17}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResModelSession from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of statistics
        if self.statistics:
            _dict['statistics'] = self.statistics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of request
        if self.request:
            _dict['request'] = self.request.to_dict()
        # set to None if closed_at (nullable) is None
        # and model_fields_set contains the field
        if self.closed_at is None and "closed_at" in self.model_fields_set:
            _dict['closedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResModelSession from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "openedAt": obj.get("openedAt"),
            "closedAt": obj.get("closedAt"),
            "statistics": ResModelSessionStatistics.from_dict(obj["statistics"]) if obj.get("statistics") is not None else None,
            "chargeUserId": obj.get("chargeUserId"),
            "chargeOrgId": obj.get("chargeOrgId"),
            "request": ResModelSessionRequest.from_dict(obj["request"]) if obj.get("request") is not None else None
        })
        return _obj


